name: PPSolution
description: A Flutter project to mirror and enhance P&P Solution website.
version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.1
  flutter_inappwebview: ^5.4.3
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true